message(STATUS "Compile for Geode 5.7.1? (y/n)")
file(READ /dev/stdin choice)
string(TOLOWER "${choice}" choice)

if(choice MATCHES "^y")
    message(STATUS "Using Geode SDK 5.7.1")
    set(GEODE_SDK_VERSION "5.7.1" PARENT_SCOPE)
else()
    message(STATUS "Skipping Geode 5.7.1")
endif()
